services:
  db01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/db01:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
    networks:
      - vprofile-net

  mc01:
    image: memcached:1.6-alpine
    networks:
      - vprofile-net

  rmq01:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    networks:
      - vprofile-net

  app01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/app-bean:latest
    ports:
      - "80:8080" # لكي يفتح التطبيق مباشرة على منفذ الويب
    depends_on:
      - db01
      - rmq01
      - mc01
    networks:
      - vprofile-net

networks:
  vprofile-net: