services:
  db01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/db01:latest
    container_name: db01
    ports:
      - "3306:3306"  # منفذ MySQL الرئيسي
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
    networks:
      - vprofile-net

  mc01:
    image: memcached:1.6-alpine
    container_name: mc01
    ports:
      - "11211:11211"  # منفذ Memcached الرئيسي
    networks:
      - vprofile-net

  rmq01:
    image: rabbitmq:3-management-alpine
    container_name: rmq01
    ports:
      - "5672:5672"  # منفذ RabbitMQ الرئيسي
      - "15672:15672"  # منفذ واجهة الإدارة (يمكن إزالته في بيئة الإنتاج)
    # في Beanstalk، يفضل عدم فتح منافذ الإدارة خارجياً إلا للضرورة
    environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
    networks:
      - vprofile-net

  app01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/app-bean:latest
    container_name: app01
    # تمت إزالة متغيرات MySQL هنا لأنها تخص حاوية db01 فقط
    volumes:
      - app_data:/usr/local/tomcat/webapps
    ports:
      - "80:8080"  # تغيير المنفذ الخارجي إلى 80 ليتوافق مع Load Balancer افتراضياً
    depends_on:
      - db01
      - rmq01
      - mc01
    networks:
      - vprofile-net

networks:
  vprofile-net:

volumes:
  db_data: {}
  app_data: {}