
services:
  db01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/app-bean:latest
    container_name: db01
    volumes:
      - db_data:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
    networks:
      - vprofile-net

  mc01:
    image: memcached:1.6-alpine
    container_name: mc01
    networks:
      - vprofile-net

  rmq01:
    image: rabbitmq:3-management-alpine
    container_name: rmq01
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
    networks:
      - vprofile-net

  app01:
    image: 579275327561.dkr.ecr.us-east-1.amazonaws.com/app-bean:latest
    container_name: app01
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
    volumes:
      - app_data:/usr/local/tomcat/webapps
    ports:
      - "8081:8080"
    depends_on:
      - db01
      - rmq01
      - mc01
    networks:
      - vprofile-net

networks:
  vprofile-net:

volumes:
  db_data: {}
  app_data: {}

