pipeline {
    agent any

    parameters {
        string(name: 'IMAGE_TAG', defaultValue: '', description: 'Enter the ECR Image Tag/Build ID to deploy (e.g., 15)')
    }
    environment {
        AWS_REGION     = 'us-east-1'
        AWS_ACCOUNT_ID = '579275327561' 
        ECR_REPO_NAME  = 'app01'
    }

    stages {
        stage('Ansible Deploy to staging'){
            agent {
                docker { 
                    image 'alpine/ansible:latest'
                    args "-u root -v /etc/hosts:/etc/hosts -v ${WORKSPACE}:${WORKSPACE} -w ${WORKSPACE}"
                }
            }

            when {
                // التأكد أن المستخدم أدخل قيم قبل البدء
                expression { params.IMAGE_TAG != ''}
            }
            
            environment {
                NEXUS_SEC_PASS = credentials('nexuspass')
            }
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'bastion_login', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')]) {
                    sh """
                    # حل مشكلة مسارات أنسيبل للملفات المؤقتة داخل الحاوية
                    export HOME=${WORKSPACE}
                    export ANSIBLE_LOCAL_TEMP=${WORKSPACE}/.ansible/tmp
                    export ANSIBLE_REMOTE_TEMP=/tmp/.ansible/tmp
                    
                    export ANSIBLE_HOST_KEY_CHECKING=False
                    
                    # تأمين ملف مفتاح الـ SSH
                    chmod 400 \${SSH_KEY}
                    
                    ansible-playbook -i ansible/prod.inventory ansible/app-deploy.yml \
                    --user=\${SSH_USER} \
                    --private-key=\${SSH_KEY} \
                    --extra-vars "image_tag_env=${params.IMAGE_TAG} ssh_key_path=\${SSH_KEY}"
                    """
                }
            }
        }
    }
    
    post {
        always {
            script {
                def color = (currentBuild.currentResult == 'SUCCESS') ? 'good' : 'danger'
                slackSend(
                    channel: '#jenkins-cicd',
                    color: color,
                    message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} [Build: ${params.BUILD}] \nDetails: ${env.BUILD_URL}"
                )
            }
        }
    }
}