---
- name: Deploy Docker Application from ECR (Simplified)
  hosts: appsrvgrp
  become: yes

  vars:
    aws_region: "us-east-1"
    ecr_registry: "579275327561.dkr.ecr.us-east-1.amazonaws.com"
    ecr_repo_name: "app01"
    image_tag: "{{ image_tag_env | default('latest') }}"

  tasks:
    - name: Login to AWS ECR
      shell: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_registry }}"

    - name: Pull Docker Image
      shell: "docker pull {{ ecr_registry }}/{{ ecr_repo_name }}:{{ image_tag }}"

    - name: Remove Old Container if exists
      shell: "docker rm -f vprofile-app"
      failed_when: false # حتى لا يفشل الـ Playbook إذا لم يكن هناك حاوية قديمة تعمل

    - name: Run New Container
      shell: >
        docker run -d --name vprofile-app 
        --restart always 
        -p 8080:8080 
        {{ ecr_registry }}/{{ ecr_repo_name }}:{{ image_tag }}