---
- name: Deploy MySQL Database using Docker
  hosts: dbsrvgrp
  become: yes
  vars:
    project_path: "/opt/mysql-app"

  tasks:

    - name: Install prerequisites for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip 
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
        state: present

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Install Docker python module
      ansible.builtin.pip:
        name: docker
        state: present


  #-----------------------------------------------------------------------------------------------------------
  
    - name: 1. Create project directory on target server
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: 2. Copy Dockerfile to target server
      copy:
        src: ./Dockerfile
        dest: "{{ project_path }}/Dockerfile"

    - name: Ensure docker network 'vprof-net' exists
      community.docker.docker_network:
        name: vprof-net
        state: present

    - name: 3. Copy Database Backup file to target server
      copy:
        src: ./db_backup.sql
        dest: "{{ project_path }}/db_backup.sql"

    - name: 4. Build Docker Image from Dockerfile
      community.docker.docker_image:
        build:
          path: "{{ project_path }}"
        name: db01
        tag: latest
        source: build

    - name: 5. Run MySQL Docker Container
      community.docker.docker_container:
        name: db01
        image: db01:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: vprof-net
        ports:
          - "3306:3306"