---
- name: Deploy Memcached using Docker
  hosts: mcsrvgrp
  become: yes

  tasks:
    - name: Ensure docker network 'vprof-net' exists
      community.docker.docker_network:
        name: vprof-net
        state: present

    - name: Run memcache Docker Container
      community.docker.docker_container:
        name: mc01
        image: memcached:1.6-alpine
        state: started
        restart_policy: unless-stopped
        network_mode: vprof-net
        ports:
          - "11211:11211"