def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven 'MAVEN'
        jdk 'JDK17'
    }

    environment {
        SNAP_REPO = 'vprofile-snapshot'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'admin123'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vpro-maven-central'
        NEXUSIP = '172.31.40.75'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredential = 'ecr:us-east-1:awsbeancreds'
        appRegistry = '579275327561.dkr.ecr.us-east-1.amazonaws.com/vprofileapp'
        dbRegistry  = '579275327561.dkr.ecr.us-east-1.amazonaws.com/db01'
        rmqRegistry = '579275327561.dkr.ecr.us-east-1.amazonaws.com/rmq01'

        vprofileup  = 'https://579275327561.dkr.ecr.us-east-1.amazonaws.com'

        cluster = "vproappstaging"
        service = "vproapptask-service-6s9zmr5o"


    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo 'Build completed successfully.'
                    archiveArtifacts artifacts: '**/*.war'
                }
                failure {
                    echo 'Build failed.'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -s settings.xml test'
            }
            post {
                success {
                    echo 'All unit tests passed.'
                }
                failure {
                    echo 'Some unit tests failed.'
                }
            }
        }
        stage('Tests') {
            steps {
                sh 'mvn -s settings.xml test'
            }
        }
        stage('checkstyle analysis') {
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }
        stage('Sonar Analysis') {
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }
            steps {
                withSonarQubeEnv("${SONARSERVER}") {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('UploadArtifact') {
            steps {
                nexusArtifactUploader(
                  nexusVersion: 'nexus3',
                  protocol: 'http',
                  nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                  groupId: 'QA',
                  version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                  repository: "${RELEASE_REPO}",
                  credentialsId: "${NEXUS_LOGIN}",
                  artifacts: [
                    [artifactId: 'vproapp',
                     classifier: '',
                     file: 'target/vprofile-v2.war',
                     type: 'war']
                  ]
                )
            }
        }


        stage ("Build RMQ Image") {
            steps {
                script {

                dockerImage = docker.build(rmqRegistry + ":$BUILD_NUMBER", "./Docker-files/rmq/")
                }
            } 
    
        }

        stage ('Upload RMQ Image') {
            steps{
                script {
                    docker.withRegistry(vprofileup, registryCredential) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }



        stage ("Build DB Image") {
            steps {
                script {

                dockerImage = docker.build(dbRegistry + ":$BUILD_NUMBER", "./Docker-files/db/")
                }
            } 
    
        }

        stage ('Upload DB Image') {
            steps{
                script {
                    docker.withRegistry(vprofileup, registryCredential) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }



        stage ("Build App Image") {
            steps {
                script {

                dockerImage = docker.build(appRegistry + ":$BUILD_NUMBER", "./Docker-files/app/")
                }
            } 
    
        }

        stage ('Upload App Image') {
            steps{
                script {
                    docker.withRegistry(vprofileup, registryCredential) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage ('Deploy to Staging ECS') {
            steps{
                withAWS(credentials: 'awsbeancreds', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    
post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#all-devops-team',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
